/* Local, deterministic blueprint editor. No network services or inferred dimensions. */
(() => {
'use strict';
const $=id=>document.getElementById(id), G=BlueprintGeometry, F=BlueprintFurniture, clone=v=>JSON.parse(JSON.stringify(v));
const canvas=$('planCanvas'),ctx=canvas.getContext('2d'),viewer=new Blueprint3D($('threeCanvas'));
let project,image,tool='select',selected=null,pending=null,pointer=null,drag=null,history=[],future=[],suggestions=[],dirty=false;
let view={x:0,y:0,z:1}, uid=0;
const furnitureNames={'sofa':'Straight sofa','sofa-l':'Sofa + chaise','tv':'TV','tv-unit':'TV unit'};
const id=()=>`trace-${Date.now()}-${++uid}`;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6000);}
function validate(next){const check=G.validateProject(next);if(!check.errors.length)check.errors.push(...F.validate(next.furniture,next.scale,[...next.walls.flatMap(w=>[w.id,...w.openings.map(o=>o.id)]),...next.dimensions.map(d=>d.id)]));return check;}
function commit(next){const check=validate(next);if(check.errors.length){toast(check.errors[0]);inspect();draw();return false;}history.push(clone(project));if(history.length>30)history.shift();future=[];project=next;dirty=true;refresh();return true;}
function change(fn){const next=clone(project);fn(next);return commit(next);}
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(clone(project));project=from.pop();selected=null;pending=null;dirty=true;refresh();}
function screen(p){return{x:p.x*view.z+view.x,y:p.y*view.z+view.y};}
function source(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-view.x)/view.z,y:(e.clientY-r.top-view.y)/view.z};}
function snap(p){if(pending&&$('ortho').checked&&['wall','calibrate','dimension'].includes(tool)){if(Math.abs(p.x-pending.a.x)>Math.abs(p.y-pending.a.y))p.y=pending.a.y;else p.x=pending.a.x;}for(const w of project.walls)for(const q of[w.a,w.b])if(Math.hypot(p.x-q.x,p.y-q.y)*view.z<9)return{...q};return p;}
function fit(){const r=canvas.getBoundingClientRect();view.z=Math.min((r.width-36)/project.image.width,(r.height-36)/project.image.height);view.x=(r.width-project.image.width*view.z)/2;view.y=(r.height-project.image.height*view.z)/2;draw();}
function zoom(f,p={x:canvas.clientWidth/2,y:canvas.clientHeight/2}){const z=Math.min(15,Math.max(.04,view.z*f));view.x=p.x-(p.x-view.x)*z/view.z;view.y=p.y-(p.y-view.y)*z/view.z;view.z=z;draw();}
function line(a,b,color,width=1,dash=[]){a=screen(a);b=screen(b);ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([]);}
function label(p,text,color='#945d36'){p=screen(p);ctx.font='11px system-ui';const width=ctx.measureText(text).width;ctx.fillStyle='#fffffff0';ctx.fillRect(p.x-width/2-4,p.y-9,width+8,17);ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,p.x,p.y+3);}
function draw(){if(!project)return;const r=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#fafbf8';ctx.fillRect(0,0,r.width,r.height);if(image){ctx.globalAlpha=+$('imageOpacity').value/100;ctx.drawImage(image,view.x,view.y,project.image.width*view.z,project.image.height*view.z);ctx.globalAlpha=1;}
for(const w of project.walls){const active=selected?.wall===w.id;line(w.a,w.b,active?'#c87132':'#267963',active?5:3);const length=G.wallLength(w,project.scale),dx=(w.b.x-w.a.x)/length,dy=(w.b.y-w.a.y)/length;
for(const o of w.openings){const a={x:w.a.x+dx*o.offset,y:w.a.y+dy*o.offset},b={x:a.x+dx*o.width,y:a.y+dy*o.width};line(a,b,'#fff',7);line(a,b,o.type==='window'?'#579cb4':'#bd8d50',3);if(o.type==='door'){const h=o.hinge==='start'?a:b,sign=o.hinge==='start'?1:-1;const ux=dx*project.scale.x,uy=dy*project.scale.y;let last=null;for(let i=0;i<=20;i++){const t=i*Math.PI/40,p={x:h.x+o.width*(ux*sign*Math.cos(t)-uy*o.swing*Math.sin(t))/project.scale.x,y:h.y+o.width*(uy*sign*Math.cos(t)+ux*o.swing*Math.sin(t))/project.scale.y};if(last)line(last,p,'#bd8d50',1);last=p;}line(h,last,'#bd8d50',2);}}
if(active){for(const p of[w.a,w.b]){const q=screen(p);ctx.beginPath();ctx.arc(q.x,q.y,6,0,7);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#c87132';ctx.lineWidth=2;ctx.stroke();}label({x:(w.a.x+w.b.x)/2,y:(w.a.y+w.b.y)/2-12/view.z},`${length.toFixed(2)} m`);}}
drawFurniture();
if($('showDimensions').checked)for(const d of project.dimensions){line(d.a,d.b,'#a56d3e',1,[4,3]);label({x:(d.a.x+d.b.x)/2,y:(d.a.y+d.b.y)/2},d.label||`${G.wallLength(d,project.scale).toFixed(2)} m`);}
if(pending){const b=pending.b||pointer;if(b)line(pending.a,b,'#bd6b37',2,[5,3]);} $('zoomValue').textContent=Math.round(view.z*100)+'%';}
function furniturePolygon(points,color,active=false){ctx.beginPath();points.forEach((p,i)=>{const q=screen(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y);});ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.strokeStyle=active?'#c87132':'#34483f';ctx.lineWidth=active?1.8:.65;ctx.stroke();}
function drawFurniture(){for(const item of project.furniture||[]){const active=selected?.furniture===item.id;for(const part of F.polygons(item,project.scale))furniturePolygon(part.points,part.color,active);if(active){label({x:item.position.x,y:item.position.y-18/view.z},`${furnitureNames[item.type]} · ${Math.round(item.width*100)} × ${Math.round((item.type==='sofa-l'?item.chaiseDepth:item.depth)*100)} cm`,'#704b2c');}}if(tool.startsWith('place-')&&pointer){ctx.globalAlpha=.55;const item=F.defaults(tool.slice(6),'preview',pointer);for(const part of F.polygons(item,project.scale))furniturePolygon(part.points,part.color);ctx.globalAlpha=1;}}
function scene(){viewer.setScene([...G.projectToMeshes(project),...F.meshes(project.furniture||[],project.scale)],{preserveCamera:true,dimensions:$('showDimensions').checked?project.dimensions.map(d=>({a:G.pixelToWorld(d.a,project.scale),b:G.pixelToWorld(d.b,project.scale),label:d.label})):[]});viewer.setCutaway($('cutaway').checked);}
function focusFurniture(item){const polygons=F.polygons(item,project.scale),points=polygons.flatMap(p=>p.points);const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));view.z=Math.min(canvas.clientWidth/(maxX-minX+180),canvas.clientHeight/(maxY-minY+180));view.x=canvas.clientWidth/2-(minX+maxX)/2*view.z;view.y=canvas.clientHeight/2-(minY+maxY)/2*view.z;draw();}
function furnitureList(){const list=$('furnitureList');list.replaceChildren();for(const item of project.furniture||[]){const b=button(list,`${furnitureNames[item.type]} · ${Math.round(item.width*100)} cm`,()=>{setTool('select');selected={furniture:item.id};inspect();focusFurniture(item);});b.classList.toggle('active',selected?.furniture===item.id);}}
function nearest(p){let best=null;for(const w of project.walls){const dx=w.b.x-w.a.x,dy=w.b.y-w.a.y,t=Math.max(0,Math.min(1,((p.x-w.a.x)*dx+(p.y-w.a.y)*dy)/(dx*dx+dy*dy))),distance=Math.hypot(p.x-w.a.x-t*dx,p.y-w.a.y-t*dy)*view.z;if(distance<14&&(!best||distance<best.distance))best={wall:w,distance,t};}return best;}
function setTool(value){tool=value;pending=null;selected=null;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('toolHint').textContent={select:'Drag furniture to move it. Select walls to edit endpoints. R rotates selected furniture.',wall:'Click two endpoints. Escape cancels. Square walls snaps horizontal / vertical.',door:'Click a wall to insert a door. Check its width, hinge and swing below.',window:'Click a wall to insert a window. Set its width and sill below.',dimension:'Click both ends of a printed dimension, then enter its original label.',calibrate:'Click the ends of a known dimension, then enter its length below.',pan:'Drag to move the blueprint. Scroll to zoom.'}[tool]||`Click to place ${furnitureNames[tool.slice(6)]}. Escape cancels.`;document.querySelectorAll('[data-furniture]').forEach(b=>b.classList.toggle('active',tool==='place-'+b.dataset.furniture));inspect();draw();}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);let p=source(e);if(tool==='pan'||e.button===1){drag={pan:true,x:e.clientX,y:e.clientY,view:{...view}};return;}if(tool.startsWith('place-')){const item=F.defaults(tool.slice(6),id(),p);if(change(n=>(n.furniture??=[]).push(item))){setTool('select');selected={furniture:item.id};inspect();draw();}return;}if(tool==='select'){const item=[...(project.furniture||[])].reverse().find(f=>F.hitTest(f,p,project.scale));if(item){selected={furniture:item.id};drag={furniture:item.id,start:p,origin:{...item.position},before:clone(project)};inspect();draw();return;}const w=project.walls.find(w=>w.id===selected?.wall);if(w){for(const end of['a','b'])if(Math.hypot(w[end].x-p.x,w[end].y-p.y)*view.z<11){drag={wall:w.id,end,before:clone(project)};return;}}const hit=nearest(p);selected=hit?{wall:hit.wall.id}:null;inspect();draw();return;}
if(['door','window'].includes(tool)){const hit=nearest(p);if(!hit){toast('Click closer to a traced wall.');return;}const w=hit.wall,L=G.wallLength(w,project.scale),width=Math.min(tool==='door'?.8:1.1,L*.6),oid=id();if(change(n=>n.walls.find(v=>v.id===w.id).openings.push({id:oid,type:tool,offset:Math.max(0,Math.min(L-width,hit.t*L-width/2)),width,height:Math.min(tool==='door'?2.05:1.2,w.height),sill:tool==='door'?0:Math.max(0,Math.min(.9,w.height-1.2)),hinge:'start',swing:1}))){selected={wall:w.id,opening:oid};inspect();}return;}
p=snap(p);if(!pending){pending={a:p};draw();return;}if(Math.hypot(p.x-pending.a.x,p.y-pending.a.y)<2)return;pending.b=p;if(tool==='wall'){const wid=id(),a=pending.a;pending=null;if(change(n=>n.walls.push({id:wid,a,b:p,...n.defaults,openings:[]}))){selected={wall:wid};inspect();}}else{inspect();$('inspector').scrollIntoView({behavior:'smooth',block:'nearest'});}draw();});
canvas.addEventListener('pointermove',e=>{let p=source(e);if(drag?.pan){view.x=drag.view.x+e.clientX-drag.x;view.y=drag.view.y+e.clientY-drag.y;draw();return;}if(drag?.furniture){const item=project.furniture.find(f=>f.id===drag.furniture);item.position={x:drag.origin.x+p.x-drag.start.x,y:drag.origin.y+p.y-drag.start.y};draw();scene();return;}if(drag?.wall){project.walls.find(w=>w.id===drag.wall)[drag.end]=p;draw();return;}pointer=tool.startsWith('place-')?p:snap(p);if(pending||tool.startsWith('place-'))draw();});
function endDrag(){if(drag?.wall||drag?.furniture){const next=project;project=drag.before;commit(next);}drag=null;draw();}canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',()=>{if(drag?.before)project=drag.before;drag=null;refresh();});
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.001),{x:e.clientX-r.left,y:e.clientY-r.top});},{passive:false});
function field(parent,title,value,onchange,options){const wrap=document.createElement('label');wrap.className='field';const span=document.createElement('span');span.textContent=title;wrap.append(span);const input=document.createElement(options?'select':'input');if(options)for(const [val,text]of options){const o=document.createElement('option');o.value=val;o.textContent=text;input.append(o);}else input.type=typeof value==='number'?'number':'text';if(input.type==='number')input.step='0.01';input.value=value;input.addEventListener('change',()=>onchange(input.type==='number'?Number(input.value):input.value));wrap.append(input);parent.append(wrap);return input;}
function button(parent,text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=fn;parent.append(b);return b;}
function hint(parent,text){const p=document.createElement('p');p.className='hint';p.textContent=text;parent.append(p);}
function inspectFurniture(item,box,fields){$('inspectorTitle').textContent=furnitureNames[item.type];const edit=(key,value)=>change(n=>n.furniture.find(f=>f.id===item.id)[key]=value);if(item.type.startsWith('sofa'))field(fields,'Sofa shape',item.type,v=>change(n=>{const f=n.furniture.find(f=>f.id===item.id);f.type=v;if(v==='sofa-l'){f.chaiseDepth=Math.max(f.depth,f.chaiseDepth||1.6);f.chaiseWidth=Math.min(f.width,f.chaiseWidth||.85);f.chaiseSide=f.chaiseSide||'left';}}),[['sofa','Straight'],['sofa-l','With chaise']]);for(const key of['width','depth','height'])field(fields,key[0].toUpperCase()+key.slice(1)+' (cm)',Math.round(item[key]*100),v=>edit(key,v/100));field(fields,'Rotation (°)',item.rotation,v=>edit('rotation',v));field(fields,'Bottom above floor (cm)',Math.round(item.elevation*100),v=>edit('elevation',v/100));if(item.type==='sofa-l'){field(fields,'Total chaise depth (cm)',Math.round(item.chaiseDepth*100),v=>edit('chaiseDepth',v/100));field(fields,'Chaise width (cm)',Math.round(item.chaiseWidth*100),v=>edit('chaiseWidth',v/100));field(fields,'Chaise side in plan',item.chaiseSide,v=>edit('chaiseSide',v),[['left','Left at 0°'],['right','Right at 0°']]);}field(fields,'Finish',item.color,v=>edit('color',v),[['#b9b19c','Oatmeal'],['#708775','Sage'],['#b97151','Terracotta'],['#426b79','Blue'],['#ad855b','Natural oak'],['#4c382e','Walnut'],['#30383b','Charcoal']]);const actions=document.createElement('div');actions.className='actions-row';box.append(actions);button(actions,'Rotate 90°',()=>edit('rotation',(item.rotation+90)%360));button(actions,'Focus in plan',()=>focusFurniture(item));button(actions,'Focus in 3D',()=>viewer.focus(item.position.x*project.scale.x,item.position.y*project.scale.y,Math.max(item.width,item.type==='sofa-l'?item.chaiseDepth:item.depth,item.height)));button(actions,'Duplicate',()=>{const copy=clone(item);copy.id=id();copy.position.x+=.25/project.scale.x;copy.position.y+=.25/project.scale.y;if(change(n=>n.furniture.push(copy))){selected={furniture:copy.id};inspect();draw();}});hint(box,'Drag this piece in the blueprint; the 3D view follows. Dimensions are overall sizes. Check wall, door-swing and walking clearances yourself; placement is unrestricted.');if(item.type==='tv')hint(box,`Screen: approximately ${(Math.hypot(item.width*.962,item.height*.87*.94)/.0254).toFixed(1)} inches diagonal. Default: 55-inch 16:9. Overall height includes the stand; bezel and stand are schematic. Set bottom above floor to your TV-unit height.`);}
function inspect(){const box=$('inspector');box.replaceChildren();$('deleteBtn').hidden=!selected;const fields=document.createElement('div');fields.className='fields';box.append(fields);furnitureList();
const item=(project.furniture||[]).find(f=>f.id===selected?.furniture);if(item){inspectFurniture(item,box,fields);return;}
if(pending?.b&&tool==='calibrate'){ $('inspectorTitle').textContent='Calibrate this reference';let metres=1,axis='uniform';field(fields,'Printed length (m)',metres,v=>metres=v);field(fields,'Apply scale','uniform',v=>axis=v,[['uniform','Both axes'],['x','Horizontal only'],['y','Vertical only']]);button(box,'Apply calibration',()=>{const dx=Math.abs(pending.b.x-pending.a.x),dy=Math.abs(pending.b.y-pending.a.y),pixels=axis==='x'?dx:axis==='y'?dy:Math.hypot(dx,dy);if(!(metres>0&&pixels>1)){toast('Choose a nonzero span and positive length.');return;}const ok=change(n=>{if(axis!=='y')n.scale.x=metres/pixels;if(axis!=='x')n.scale.y=metres/pixels;n.scale.calibrated=true;});if(ok){pending=null;inspect();draw();}});hint(box,'Use both axes for an undistorted scan. Calibrate X and Y separately only when the reference is stretched. Existing openings are not resized silently.');return;}
if(pending?.b&&tool==='dimension'){ $('inspectorTitle').textContent='Preserve a source measurement';let text='',metres=G.wallLength(pending,project.scale);field(fields,'Original label','',v=>text=v);field(fields,'Source length (m)',metres,v=>metres=v);button(box,'Add measurement',()=>{const d={id:id(),a:pending.a,b:pending.b,label:text||`${metres.toFixed(2)} m`,metres};if(change(n=>n.dimensions.push(d))){pending=null;inspect();draw();}});return;}
const d=project.dimensions.find(d=>d.id===selected?.dimension);if(d){$('inspectorTitle').textContent='Source measurement';field(fields,'Original label',d.label,v=>change(n=>n.dimensions.find(x=>x.id===d.id).label=v));field(fields,'Source length (m)',d.metres||G.wallLength(d,project.scale),v=>change(n=>n.dimensions.find(x=>x.id===d.id).metres=v));hint(box,`Calibrated trace: ${G.wallLength(d,project.scale).toFixed(3)} m. Labels do not change the wall geometry.`);return;}
const w=project.walls.find(w=>w.id===selected?.wall);if(w){const o=w.openings.find(o=>o.id===selected.opening);const edit=(key,value)=>change(n=>{const wall=n.walls.find(x=>x.id===w.id);(o?wall.openings.find(x=>x.id===o.id):wall)[key]=value;});$('inspectorTitle').textContent=o?`${o.type==='door'?'Door':'Window'} properties`:'Wall properties';if(o){for(const key of['offset','width','height',...(o.type==='window'?['sill']:[])])field(fields,key[0].toUpperCase()+key.slice(1)+' (m)',o[key],v=>edit(key,v));if(o.type==='door'){field(fields,'Hinge',o.hinge,v=>edit('hinge',v),[['start','Start of opening'],['end','End of opening']]);field(fields,'Swing side',o.swing,v=>edit('swing',+v),[['1','Side +'],['-1','Side −']]);}button(box,'Back to wall',()=>{selected={wall:w.id};inspect();});}else{field(fields,'Length (m)',+G.wallLength(w,project.scale).toFixed(3),v=>change(n=>{const wall=n.walls.find(x=>x.id===w.id),factor=v/G.wallLength(w,n.scale);wall.b={x:wall.a.x+(wall.b.x-wall.a.x)*factor,y:wall.a.y+(wall.b.y-wall.a.y)*factor};}));for(const key of['height','thickness'])field(fields,key+' (m)',w[key],v=>edit(key,v));for(const end of['a','b'])for(const axis of['x','y'])field(fields,`${end.toUpperCase()} ${axis} (px)`,+w[end][axis].toFixed(2),v=>change(n=>n.walls.find(x=>x.id===w.id)[end][axis]=v));const list=document.createElement('div');list.className='opening-list';box.append(list);w.openings.forEach((o,i)=>button(list,`${o.type} ${i+1} · ${o.width.toFixed(2)} m`,()=>{selected={wall:w.id,opening:o.id};inspect();}));}hint(box,'Height and thickness require confirmation. Offsets run from endpoint A. Door arcs must match the source plan.');return;}
$('inspectorTitle').textContent='Project settings';field(fields,'Project name',project.name,v=>change(n=>n.name=v));field(fields,'New wall height (m)',project.defaults.height,v=>change(n=>n.defaults.height=v));field(fields,'New wall thickness (m)',project.defaults.thickness,v=>change(n=>n.defaults.thickness=v));hint(box,'1. Upload a plan. 2. Set scale from a printed dimension. 3. Trace walls or review suggested lines. 4. Add doors, windows and source labels. Every edit updates 3D.');hint(box,'Tracing follows your clicks; raster images cannot guarantee survey accuracy. Heights, wall thickness and opening details remain your explicit inputs.');}
function refresh(){const report=validate(project);$('projectName').textContent=project.name;$('accuracyBadge').textContent=project.scale.calibrated?'Calibrated trace · review required':'Scale not set';$('imageMeta').textContent=`${project.image.width} × ${project.image.height} px`;$('wallCount').textContent=project.walls.length+' walls';$('openingCount').textContent=project.walls.reduce((s,w)=>s+w.openings.length,0)+' openings';$('undoBtn').disabled=!history.length;$('redoBtn').disabled=!future.length;$('scaleSummary').textContent=`X: ${(project.scale.x*1000).toFixed(3)} mm/px · Y: ${(project.scale.y*1000).toFixed(3)} mm/px · ${project.scale.calibrated?'Reference calibrated; source labels checked below.':'Uncalibrated visual estimate.'}`;$('measurements').replaceChildren();project.dimensions.forEach(d=>{const measured=G.wallLength(d,project.scale),mismatch=d.metres&&Math.abs(measured-d.metres)>Math.max(.03,d.metres*.02),b=button($('measurements'),`${d.label} · trace ${measured.toFixed(2)} m`,()=>{selected={dimension:d.id};inspect();draw();});b.className='measure-chip'+(mismatch?' mismatch':'');});$('warnings').replaceChildren();for(const warning of [...report.warnings,'Wall heights, thicknesses and opening properties must be checked against the actual home.']){const li=document.createElement('li');li.textContent=warning;$('warnings').append(li);}$('reviewSummary').textContent=`Review notes · ${report.warnings.length} scale checks`;$('projectNotes').textContent=project.notes;scene();inspect();draw();}
function deleteSelected(){if(!selected)return;const s=selected;selected=null;change(n=>{if(s.furniture)n.furniture=n.furniture.filter(f=>f.id!==s.furniture);else if(s.dimension)n.dimensions=n.dimensions.filter(d=>d.id!==s.dimension);else if(s.opening){const w=n.walls.find(w=>w.id===s.wall);w.openings=w.openings.filter(o=>o.id!==s.opening);}else n.walls=n.walls.filter(w=>w.id!==s.wall);});}
async function load(next){const check=validate(next);if(check.errors.length)throw Error(check.errors[0]);if(next.walls.length>1000||next.dimensions.length>1000||next.walls.reduce((s,w)=>s+w.openings.length,0)>2000)throw Error('Project is too large (maximum 1000 walls / dimensions, 2000 openings).');if(next.image.width*next.image.height>20000000)throw Error('Use a blueprint of 20 megapixels or less.');const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Cannot read the project image.'));img.src=next.image.src;});if(img.naturalWidth!==next.image.width||img.naturalHeight!==next.image.height)throw Error('Image dimensions do not match project metadata.');project=clone(next);project.furniture??=[];image=img;history=[];future=[];selected=null;pending=null;dirty=false;refresh();viewer.reset();fit();}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const filename=()=>project.name.replace(/[^a-z0-9_-]+/gi,'-').slice(0,70)||'blueprint';
function replaceOkay(){return !dirty||confirm('Replace the current project? Save it first if you want to keep your edits.');}
$('uploadBtn').onclick=()=>$('imageInput').click();$('importBtn').onclick=()=>$('projectInput').click();
$('imageInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||!replaceOkay())return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12*1024*1024)throw Error('Choose a PNG, JPG or WebP smaller than 12 MB.');const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image cannot be decoded.'));img.src=src;});await load({version:1,name:file.name.replace(/\.[^.]+$/,''),image:{src,width:img.naturalWidth,height:img.naturalHeight},scale:{x:.01,y:.01,calibrated:false},defaults:{height:2.5,thickness:.12},walls:[],dimensions:[],notes:'Uploaded raster reference. Trace lines and verify openings manually. Printed dimensions are transcribed, not automatically recognised.'});setTool('calibrate');toast('Blueprint loaded. Set scale, then trace walls or review suggested lines.');}catch(error){toast(error.message);}};
$('projectInput').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f||!replaceOkay())return;try{if(f.size>16*1024*1024)throw Error('Project file exceeds 16 MB.');await load(JSON.parse(await f.text()));toast('Project opened.');}catch(error){toast('Project rejected: '+error.message);}};
$('saveBtn').onclick=()=>{download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),filename()+'.json');dirty=false;toast('Project saved with image, geometry and measurements.');};
$('deleteBtn').onclick=deleteSelected;$('undoBtn').onclick=()=>undo();$('redoBtn').onclick=()=>undo(true);$('fitBtn').onclick=fit;$('zoomIn').onclick=()=>zoom(1.3);$('zoomOut').onclick=()=>zoom(1/1.3);$('imageOpacity').oninput=draw;$('showDimensions').onchange=refresh;$('reset3d').onclick=()=>viewer.reset();$('cutaway').onchange=()=>viewer.setCutaway($('cutaway').checked);$('captureBtn').onclick=()=>{try{const a=document.createElement('a');a.href=viewer.screenshot();a.download=filename()+'-3d.png';a.click();}catch(e){toast(e.message);}};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-furniture]').forEach(b=>b.onclick=()=>setTool('place-'+b.dataset.furniture));$('demoBtn').onclick=()=>{if(replaceOkay())load(window.BLUEPRINT_DEMO).catch(e=>toast(e.message));};$('clearBtn').onclick=()=>{if(confirm('Remove all traces and measurements? The image will remain. You can undo this.')){selected=null;change(n=>{n.walls=[];n.dimensions=[];});}};
$('suggestBtn').onclick=()=>{const c=document.createElement('canvas'),factor=Math.min(1,1400/Math.max(image.width,image.height));c.width=Math.round(image.width*factor);c.height=Math.round(image.height*factor);const context=c.getContext('2d');context.drawImage(image,0,0,c.width,c.height);suggestions=G.suggestWalls(context.getImageData(0,0,c.width,c.height)).map(w=>({a:{x:w.a.x/factor,y:w.a.y/factor},b:{x:w.b.x/factor,y:w.b.y/factor}}));$('suggestCount').textContent=`${suggestions.length} candidates found. They may cover the entire image, including other apartments.`;$('suggestDialog').showModal();};$('cancelSuggest').onclick=()=>$('suggestDialog').close();$('acceptSuggest').onclick=()=>{change(n=>{for(const w of suggestions)n.walls.push({id:id(),...w,...n.defaults,openings:[]});n.notes+=' Suggested ink lines added; every candidate requires manual review.';});$('suggestDialog').close();};
const xml=s=>String(s).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
$('exportSvg').onclick=()=>{let content=`<svg xmlns="http://www.w3.org/2000/svg" width="${project.image.width}" height="${project.image.height}" viewBox="0 0 ${project.image.width} ${project.image.height}"><image href="${xml(project.image.src)}" width="100%" height="100%" opacity=".65"/>`;for(const w of project.walls){content+=`<line x1="${w.a.x}" y1="${w.a.y}" x2="${w.b.x}" y2="${w.b.y}" stroke="#267963" stroke-width="4"/>`;for(const o of w.openings){const L=G.wallLength(w,project.scale),dx=(w.b.x-w.a.x)/L,dy=(w.b.y-w.a.y)/L;content+=`<line x1="${w.a.x+dx*o.offset}" y1="${w.a.y+dy*o.offset}" x2="${w.a.x+dx*(o.offset+o.width)}" y2="${w.a.y+dy*(o.offset+o.width)}" stroke="${o.type==='door'?'#bd8d50':'#579cb4'}" stroke-width="8"/>`;if(o.type==='door'){const hx=w.a.x+dx*(o.offset+(o.hinge==='end'?o.width:0)),hy=w.a.y+dy*(o.offset+(o.hinge==='end'?o.width:0)),ux=dx*project.scale.x,uy=dy*project.scale.y,sign=o.hinge==='start'?1:-1;let points=[];for(let i=0;i<=20;i++){const t=i*Math.PI/40;points.push(`${hx+o.width*(ux*sign*Math.cos(t)-uy*o.swing*Math.sin(t))/project.scale.x},${hy+o.width*(uy*sign*Math.cos(t)+ux*o.swing*Math.sin(t))/project.scale.y}`);}content+=`<polyline points="${points.join(' ')}" fill="none" stroke="#bd8d50"/><polyline points="${hx},${hy} ${points[20]}" fill="none" stroke="#bd8d50" stroke-width="2"/>`;}}}for(const item of project.furniture||[])for(const part of F.polygons(item,project.scale))content+=`<polygon points="${part.points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="${part.color}" stroke="#34483f" stroke-width=".7"/>`;for(const d of project.dimensions)content+=`<line x1="${d.a.x}" y1="${d.a.y}" x2="${d.b.x}" y2="${d.b.y}" stroke="#945d36" stroke-dasharray="4 3"/><text x="${(d.a.x+d.b.x)/2}" y="${(d.a.y+d.b.y)/2}" fill="#945d36" font-size="14">${xml(d.label)}</text>`;content+='<text x="20" y="25" font-family="sans-serif" font-size="14">Green: wall traces · Gold: doors / source dimensions · Blue: windows. Review required.</text></svg>';download(new Blob([content],{type:'image/svg+xml'}),filename()+'-2d.svg');};
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);}if(e.key==='Escape'){pending=null;if(drag?.before)project=drag.before;drag=null;if(tool.startsWith('place-'))setTool('select');refresh();}if(e.key.toLowerCase()==='r'&&selected?.furniture){const fid=selected.furniture;change(n=>{const f=n.furniture.find(f=>f.id===fid);f.rotation=(f.rotation+90)%360;});}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteSelected();}});
new ResizeObserver(()=>{draw();viewer.resize();}).observe($('planStage'));
window.blueprintApp={getProject:()=>clone(project)};
load(window.BLUEPRINT_DEMO).catch(e=>toast('Example could not load: '+e.message));
})();
